version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8031:8031"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro