//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace Database
{
	/// <summary>
	/// Database       : TestApiDb
	/// Data Source    : localhost
	/// Server Version : 14.00.3370
	/// </summary>
	public partial class TestApiDb : LinqToDB.Data.DataConnection
	{
		public ITable<Users> Users { get { return this.GetTable<Users>(); } }

		public TestApiDb()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestApiDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Users")]
	public partial class Users
	{
		[Column(DataType=DataType.Int32), NotNull] public int UserId { get; set; } // int
	}
}

#pragma warning restore 1591
